# 1.8. Матрицы. Основные понятия

In [1]:
import numpy as np
a=np.array([[1,-5,3],[2,2,1],[0,3,1],[2,4,12]])
a

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [2]:
a.shape

(4, 3)

In [3]:
a[1,2]

1

In [4]:
a[2,1]

3

In [5]:
a[2,2]

1

# 1.9. Базовые действия над матрицами

In [6]:
a+a

array([[  2, -10,   6],
       [  4,   4,   2],
       [  0,   6,   2],
       [  4,   8,  24]])

In [7]:
a*3

array([[  3, -15,   9],
       [  6,   6,   3],
       [  0,   9,   3],
       [  6,  12,  36]])

In [8]:
a1=np.matrix('1,-5;2,2;0,3')
b=np.array([7,5,1])

In [9]:
a1

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [10]:
a1.T

matrix([[ 1,  2,  0],
        [-5,  2,  3]])

In [11]:
b

array([7, 5, 1])

In [12]:
b.T

array([7, 5, 1])

# 1.10. --> Практика. Базовые действия над матрицами

In [13]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [16]:
Inc=np.matrix([Husband_Income,Wife_Income,Mother_In_Law_Income])
Inc=Inc.T
Inc

matrix([[100, 150,  90],
        [220, 200,  80],
        [140, 130, 100]])

In [18]:
Cons=np.matrix([Husband_Сonsumption,Wife_Сonsumption,Mother_In_Law_Сonsumption])
Cons=Cons.T
Cons

matrix([[ 50, 100, 100],
        [ 50,  80,  20],
        [ 60, 140, 140]])

In [21]:
IncN=Inc*0.87
IncN

matrix([[ 87. , 130.5,  78.3],
        [191.4, 174. ,  69.6],
        [121.8, 113.1,  87. ]])

In [23]:
P=IncN-Cons
P

matrix([[ 37. ,  30.5, -21.7],
        [141.4,  94. ,  49.6],
        [ 61.8, -26.9, -53. ]])

# 1.11. Умножение матриц

In [24]:
A=np.matrix('1,-5;2,2;0,3')
B=np.matrix('3,1,0;-1,0,2')

In [27]:
np.dot(A,B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [28]:
np.dot(B,A)

matrix([[  5, -13],
        [ -1,  11]])

# 1.12. Умножение на специальные матрицы

Нулевая и единичная матрица играют роль нуля и единицы в матричном умножении.
Умножение на шаровую матрицу — то же самое, что умножение на скаляр.
Умножение на диагональную матрицу даёт растяжение каждого столбца или строки в зависимости от порядка.
Диагональные матрицы коммутируют между собой.

# 1.13. Делители нуля

Делители нуля — это специальные ненулевые элементы, которые дают ноль при умножении.

# 1.14. Умножение и транспонирование матриц

In [34]:
gram=np.array([[1,1],[2,-1],[1,2]])
gramT=gram.T
np.dot(gram,gramT)

array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])

# 1.15. --> Практика. Умножение матриц

In [40]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
A@x

array([26, 30])