# 1.8. Матрицы. Основные понятия

In [1]:
import numpy as np
a=np.array([[1,-5,3],[2,2,1],[0,3,1],[2,4,12]])
a

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [2]:
a.shape

(4, 3)

In [3]:
a[1,2]

1

In [4]:
a[2,1]

3

In [5]:
a[2,2]

1

# 1.9. Базовые действия над матрицами

In [6]:
a+a

array([[  2, -10,   6],
       [  4,   4,   2],
       [  0,   6,   2],
       [  4,   8,  24]])

In [7]:
a*3

array([[  3, -15,   9],
       [  6,   6,   3],
       [  0,   9,   3],
       [  6,  12,  36]])

In [8]:
a1=np.matrix('1,-5;2,2;0,3')
b=np.array([7,5,1])

In [9]:
a1

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [10]:
a1.T

matrix([[ 1,  2,  0],
        [-5,  2,  3]])

In [11]:
b

array([7, 5, 1])

In [12]:
b.T

array([7, 5, 1])

# 1.10. --> Практика. Базовые действия над матрицами

In [2]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [16]:
Inc=np.matrix([Husband_Income,Wife_Income,Mother_In_Law_Income])
Inc=Inc.T
Inc

matrix([[100, 150,  90],
        [220, 200,  80],
        [140, 130, 100]])

In [18]:
Cons=np.matrix([Husband_Сonsumption,Wife_Сonsumption,Mother_In_Law_Сonsumption])
Cons=Cons.T
Cons

matrix([[ 50, 100, 100],
        [ 50,  80,  20],
        [ 60, 140, 140]])

In [21]:
IncN=Inc*0.87
IncN

matrix([[ 87. , 130.5,  78.3],
        [191.4, 174. ,  69.6],
        [121.8, 113.1,  87. ]])

In [23]:
P=IncN-Cons
P

matrix([[ 37. ,  30.5, -21.7],
        [141.4,  94. ,  49.6],
        [ 61.8, -26.9, -53. ]])

# 1.11. Умножение матриц

In [24]:
A=np.matrix('1,-5;2,2;0,3')
B=np.matrix('3,1,0;-1,0,2')

In [27]:
np.dot(A,B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [28]:
np.dot(B,A)

matrix([[  5, -13],
        [ -1,  11]])

# 1.12. Умножение на специальные матрицы

Нулевая и единичная матрица играют роль нуля и единицы в матричном умножении.
Умножение на шаровую матрицу — то же самое, что умножение на скаляр.
Умножение на диагональную матрицу даёт растяжение каждого столбца или строки в зависимости от порядка.
Диагональные матрицы коммутируют между собой.

# 1.13. Делители нуля

Делители нуля — это специальные ненулевые элементы, которые дают ноль при умножении.

# 1.14. Умножение и транспонирование матриц

In [34]:
gram=np.array([[1,1],[2,-1],[1,2]])
gramT=gram.T
np.dot(gram,gramT)

array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])

# 1.15. --> Практика. Умножение матриц

In [4]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
A@x

array([26, 30])

In [6]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [17]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
xyz=np.matrix([x,y,z])
xyz*xyz.T

matrix([[22,  3,  0],
        [ 3,  7,  0],
        [ 0,  0,  3]])

In [32]:
import pandas as pd
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [35]:
Count_NP=Count_DF.values
Price_NP=Price_DF.values
Count_NP[1]*Price_NP[1]

array([ 3.6, 52.5,  3. , 25. ,  6. ])

In [36]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
(Count_NP*Price_NP)@com

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [38]:
(Count_NP*Price_NP)@(np.ones(5)-com)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

# 1.16. Обратная матрица

In [39]:
K=np.matrix('1,2,3;4,5,6;7,8,10')
np.linalg.inv(K)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

# 1.17. Определитель матрицы

In [40]:
K=np.matrix('1,2,3;4,5,6;7,8,10')
np.linalg.det(K)

-2.9999999999999982

In [43]:
diagonal=np.diag([2,1,4])
np.linalg.det(diagonal)

7.999999999999998

In [45]:
np.linalg.det(np.linalg.inv(diagonal))

0.12500000000000003

# 1.19. Линейная (не)зависимость ч.2