# 1.2. Векторы. Основные понятия

In [1]:
import numpy as np
s= np.array([33,65,50,45])
s

array([33, 65, 50, 45])

In [2]:
s[2]

50

In [3]:
len(s)

4

In [14]:
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2], dtype=float)
share_living_space = apartment[1]/apartment[0]
apartment = np.delete(apartment, [0, 1])
apartment = np.append(apartment, share_living_space)
apartment[-1:]

array([0.52773109])

In [15]:
len(apartment)

5

# 1.3. Базовые операции над векторами

In [16]:
a= np.array([10,8,5,1])
b= np.array([5,15,9,7])

In [17]:
a+b

array([15, 23, 14,  8])

In [18]:
a-b

array([ 5, -7, -4, -6])

In [19]:
o= np.array([120,45,68])
omega = 0.2
o*omega

array([24. ,  9. , 13.6])

In [20]:
a1=np.array([120,150,90])
a2=np.array([130,130,130])
a3=np.array([2,3,2.5])
a3=a3*72
a3

array([144., 216., 180.])

In [21]:
a1+a2+a3

array([394., 496., 400.])

# 1.4. Линейная комбинация векторов

In [22]:
premium=np.array([2,4,5])
vip=np.array([8,10,2])
standart=np.array([0,12,7])
sum=premium*500+vip*100+standart*0
sum

array([1800, 3000, 2700])

In [23]:
s1=np.array([4,5])
s2=np.array([2,1])
s3=np.array([1,0])
s4=s1*2+s2*-3+s3*5
s4

array([7, 7])

In [24]:
w1=np.array([3,4,5,9])
w2=np.array([1,5,3,6])
w3=w2*400-w1*200
w3

array([-200, 1200,  200,  600])

# 1.5. Скалярное произведение векторов

In [27]:
b1=np.array([65,70,120,30])
b2=np.array([0.4,0.4,0.2,0.8])
np.dot(b1,b2)

102.0

# 1.6. Векторы. Практическая задача