## 5. Модуль NumPy. Типы данных

### 5. Модуль NumPy. Типы данных

In [1]:
import numpy as np
a = np.int8(25)
print(type(a))

<class 'numpy.int8'>


In [24]:
np.iinfo(a)

iinfo(min=-128, max=127, dtype=int8)

In [71]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [26]:
b = np.uint8(124)
print(type(b))
print(np.iinfo(b))
print(np.iinfo(np.uint64))

<class 'numpy.uint8'>
Machine parameters for uint8
---------------------------------------------------------------
min = 0
max = 255
---------------------------------------------------------------

Machine parameters for uint64
---------------------------------------------------------------
min = 0
max = 18446744073709551615
---------------------------------------------------------------



In [27]:
a=np.uint8(-456)
a

56

### 6. Модуль NumPy. Массивы

In [28]:
arr = np.array([1,5,2,9,10])
arr

array([ 1,  5,  2,  9, 10])

In [29]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [30]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [31]:
arr = np.array([345234, 876362.12, 0, -1000, 99999999], dtype=np.float32)
arr

array([ 3.452340e+05,  8.763621e+05,  0.000000e+00, -1.000000e+03,
        1.000000e+08], dtype=float32)

In [32]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [33]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
zeros_3d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [34]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [35]:
arr = np.linspace(1, 2, 10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [36]:
arr, step = np.linspace(-6, 21, 60, endpoint=True, retstep=True)
print(round(step,2))

0.46


In [37]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(round(step,2))

0.45


In [ ]:
# для задания на платформе:
from hidden import mystery
import numpy as np
print(mystery.ndim)
print(mystery.shape)
print(mystery.size)
print(mystery.dtype)
print(mystery.itemsize*mystery.size)

### 7. Модуль NumPy. Действия с массивами

In [38]:
#создать массив 1 размерный
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
#создать массив 2 размерный (строка, столбец)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [40]:
#создать новый массив из имеющегося
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
#обратное заполнение, теперь по столбцам
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [42]:
#транспорирование
arr = np.arange(8)
arr.shape = (2, 4)
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [ ]:
#задача с платформы:
try:
    from Root.src.hidden import mystery
except ImportError:
    from hidden import mystery
# В переменную elem_5_3 сохраните элемент из 5 строки и 3 столбца:
elem_5_3 = mystery[4, 2]
# В переменную last сохраните элемент из последней строки последнего столбца
last = mystery[-1, -1]
# В переменную line_4 сохраните строку 4
line_4 = mystery[3, :]
# В переменную col_2 сохраните предпоследний столбец
col_2 = mystery[:, -2]
# Из строк 2-4 (включительно) получите столбцы 3-5 (включительно). Результат сохраните в переменную part
part = mystery[1:4, 2:5]
#  Сохраните в переменную rev последний столбец в обратном порядке
rev = mystery[:, -1]
rev = rev[::-1]
# Сохраните в переменную trans транспонированный массив
trans = mystery.transpose()

In [43]:
#СОРТИРОВКА ОДНОМЕРНЫХ МАССИВОВ
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr_new)

arr1 = np.array([23,12,45,12,23,4,15,3])
arr1.sort()
print(arr1)

[ 3  4 12 12 15 23 23 45]
[ 3  4 12 12 15 23 23 45]


In [44]:
#РАБОТА С ПРОПУЩЕННЫМИ ДАННЫМИ
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data)
roots

<ipython-input-44-29a3464af5aa>:3: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [45]:
#узнаем, на каких местах в массиве находятся «не числа»
np.isnan(roots)

array([False, False,  True, False])

In [46]:
roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [ ]:
#тест на платформе:
try:
    from Root.src.hidden import mystery
except ImportError:
    from hidden import mystery
# Получите булевый массив с информацией о np.nan в массиве mystery
# True - значение пропущено, False - значение не пропущено
print(mystery)
import numpy as np
nans_index = np.isnan(mystery)
print(nans_index)

# В переменную n_nan сохраните число пропущенных значений
n_nan = sum(nans_index)
print(n_nan)

# Заполните пропущенные значения в массиве mystery нулями
mystery[np.isnan(mystery)] = 0
print(mystery)

# Поменяйте тип данных в массиве mystery на int32
mystery=np.int32(mystery)
print('!!!!!!!!!!')
print(type(mystery))
print('!!!!!!!!!!')

# Отсортируйте значения в массиве по возрастанию и сохраните
# результат в переменную array
array = np.sort(mystery)
print(array)

# Сохраните в массив table двухмерный массив, полученный из массива array
# В нём должно быть 5 строк и 3 столбца. Причём порядок заполнения должен быть
# по столбцам! Например, 1, 2, 3, 4 -> 1    3
#                                      2    4
table = array.reshape((5, 3), order='F')
print(table)

#  Сохраните в переменную col средний столбец из table
col = table[:,1]
print(col)

### 8. Модуль NumPy. Операции с векторами

##### ВЕКТОРЫ В NUMPY И АРИФМЕТИКА

In [47]:
#сложение:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [48]:
#умножение:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [49]:
#умножение на число:
vec = np.arange(5)
vec * 10

array([ 0, 10, 20, 30, 40])

In [50]:
#возвести в степень:
vec = np.arange(5)
vec ** 2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [51]:
#сравнивать поэлементно:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 > vec2

array([False, False,  True, False])

In [52]:
#сравнивать с числом:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

#### ПРОДВИНУТЫЕ ОПЕРАЦИИ С ВЕКТОРАМИ

In [53]:
vec = np.array([3, 4])
#подмодуль LINALG позволяет производить операции из линейной алгебры
#NORM - длина вектора
length = np.linalg.norm(vec)
length

5.0

In [54]:
#расстояние между векторами:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702

In [55]:
#скалярное произведение:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
print(scalar_product)

scalar_product = np.dot(vec1, vec2)
print(scalar_product)

250.0
250.0


In [56]:
a = np.array([23, 34, 27])
b = np.array([-54, 1,  46])
c = np.array([46, 68, 54])
#сумма длин сонаправленных векторов должна быть равной длине суммы двух векторов,
#с помощью этого критерия найдите пару сонаправленных векторов:
len_a = np.linalg.norm(a)
len_b = np.linalg.norm(b)
len_c = np.linalg.norm(c)
 
len_a_b = np.linalg.norm(a + b)
len_b_c = np.linalg.norm(b + c)
len_a_c = np.linalg.norm(a + c)
 
print(len_a_b == len_a + len_b)
print(len_b_c == len_b + len_c)
print(len_a_c == len_a + len_c)

False
False
True


In [57]:
#Найдите пару векторов, расстояние между которыми больше 100:
len_a_b = np.linalg.norm(a - b)
len_b_c = np.linalg.norm(b - c)
len_a_c = np.linalg.norm(a - c)
 
print(len_a_b)
print(len_b_c)
print(len_a_c)

85.901105930017
120.6358155772986
49.13247398615299


In [58]:
#Найдите пару перпендикулярных векторов с помощью скалярного произведения:
len_a_b = np.dot(a , b)
len_b_c = np.dot(b , c)
len_a_c = np.dot(a , c)
 
print(len_a_b)
print(len_b_c)
print(len_a_c)

34
68
4828


#### БАЗОВЫЕ СТАТИСТИЧЕСКИЕ ФУНКЦИИ ДЛЯ ВЕКТОРОВ

In [59]:
#максимальное и минимальное значение в векторе:
vec = np.array([2,7,18,28,18,1,8,4])
print(vec.min())
print(np.max(vec))

1
28


In [60]:
#среднее значение:
np.mean(vec)

10.75

In [61]:
np.median(vec)

7.5

In [ ]:
#задание на платформе:
from hidden import mystery
import numpy as np
print(np.min(mystery))
print(np.mean(mystery))
print(np.median(mystery))
print(round(np.std(mystery),2))

### 9. Модуль NumPy. Случайные числа

In [2]:
#подмодуль random - генерации псевдослучайных чисел, 
#rand - генерирует число с плавающей точкой между 0 (включительно) и 1 (не включительно):
np.random.rand()

0.21141840019564595

In [3]:
np.random.rand() * 100

83.59848067865167

In [4]:
np.random.rand(5)

array([0.40666085, 0.61294437, 0.78482129, 0.13538425, 0.5752365 ])

In [5]:
np.random.rand(2, 3)

array([[0.58128951, 0.88086508, 0.1894091 ],
       [0.49706207, 0.49928784, 0.65684502]])

In [6]:
np.random.rand(2, 3, 4, 10, 12, 23)

array([[[[[[1.31562866e-01, 2.60577333e-01, 5.31432595e-01, ...,
            2.80030671e-01, 3.37705674e-01, 2.79248838e-02],
           [1.13824764e-01, 8.51339602e-01, 8.26494078e-01, ...,
            2.00602301e-01, 4.88433486e-01, 3.99619985e-02],
           [5.91202127e-01, 9.20588387e-01, 3.81456830e-01, ...,
            9.88511423e-02, 9.53623096e-01, 4.61934721e-01],
           ...,
           [3.14020928e-01, 9.90466795e-01, 3.17309265e-01, ...,
            8.36386328e-01, 7.53054238e-01, 6.46407482e-02],
           [1.95220064e-01, 6.57358059e-01, 7.02993247e-01, ...,
            3.57635830e-01, 1.69340505e-01, 3.52915169e-01],
           [9.17743972e-01, 3.72905586e-01, 7.87032201e-01, ...,
            2.88334418e-01, 3.85583214e-01, 1.30313249e-01]],

          [[9.71171791e-01, 9.09844862e-01, 1.93692432e-02, ...,
            6.13416722e-01, 4.83298893e-01, 5.88980001e-01],
           [6.19875002e-01, 1.49791304e-01, 9.48042040e-01, ...,
            2.77295563e-01, 7.53338

In [7]:
#принимает в качестве аргумента именно кортеж без распаковки SAMPLE:
shape = (2, 3)
np.random.sample(shape)

array([[0.6852798 , 0.9067561 , 0.02179314],
       [0.1464782 , 0.74489973, 0.65574237]])

#### uniform

In [8]:
np.random.uniform()

0.6811754410499452

In [9]:
np.random.uniform(-30, 50)

-10.14613528984065

In [10]:
np.random.uniform(0.5, 0.75, size=5)

array([0.65316507, 0.62571089, 0.55099531, 0.57227899, 0.65552465])

In [11]:
np.random.uniform(-1000, 500, size=(2, 3))

array([[-955.16895044, -438.40588418,  417.82225588],
       [-615.98056521, -395.14962994, -301.27542836]])

In [12]:
#randint типа данных dtype=int
np.random.randint(6, 12, size=(3,3))

array([[10,  8,  8],
       [ 7,  7, 11],
       [ 7,  6, 11]])

In [15]:
#shuffle:
arr = np.arange(6)
np.random.shuffle(arr)
arr

array([0, 4, 5, 1, 2, 3])

In [16]:
#permutation:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
print(playlist)

['ACDC' 'Deep Purple' 'Pink Floyd' 'The Beatles']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [17]:
np.random.permutation(10)

array([8, 0, 5, 1, 7, 3, 6, 2, 9, 4])

In [20]:
#choice:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
choice = np.random.choice(workers, size=2, replace=False)
print(choice)

['John' 'Ivan']


In [21]:
#seed:
np.random.seed(23)
np.random.randint(10, size=(3,4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [22]:
np.random.seed(100)
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))

[8 8 3]
[7 7 0]
[4 2 5]


In [70]:
# Не забудьте импортировать numpy и сразу задать seed 2021
import numpy as np
np.random.seed(2021)

# В simple сохранте случайное число в диапазоне от 0 до 1
simple = np.random.rand()
print(simple)
# Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их
# в переменную randoms
randoms = np.random.uniform(-150, 2021, size=120)
print(randoms)
# Получите массив из случайных целых чисел от 1 до 100 (включительно)
# из 3 строк и 2 столбцов. Сохраните результат в table
table = np.random.randint(1, 101, size=(3,2))
print(table)
# В переменную even сохраните четные числа от 2 до 16 (включительно)
even = np.arange(2,17,2)
print(even)
# Перемешайте числа в even так, чтобы массив even изменился
np.random.shuffle(even)
print(even)
# Получите из even 3 числа без повторений. Сохраните их в переменную select
select = np.random.choice(even, size=3, replace=False)
print(select)
# Получите переменную triplet, которая должна содержать перемешанные
# значения из массива select (сам select измениться не должен)
triplet = np.random.permutation(select)
print(triplet)

0.6059782788074047
[ 1.44214488e+03  1.51654277e+02  5.28813265e+02  2.01501516e+03
  1.28240517e+02  2.38594033e+02  1.48460111e+03  1.28755048e+03
  1.55273730e+03  6.03577336e+01 -2.28417401e+01  1.93936169e+03
  1.18854621e+03  3.80736459e+01  1.06852230e+03  1.18847514e+03
  1.94250320e+03  1.09681462e+03  6.55790201e+02  8.31607324e+02
  2.88216888e+02  1.08596141e+03  2.73553360e+02  1.11722142e+03
  8.84076551e+02  9.74175063e+02  1.63694713e+03  1.43966053e+03
 -7.88273550e-02  1.30919192e+03  1.24700551e+03  1.64761920e+03
  2.93903055e+02  1.19056852e+03  1.19102890e+03  5.03619976e+02
  1.74254881e+03  1.13013901e+03  1.98142287e+03  8.10086179e+02
  1.24235695e+02  9.54671885e+02  7.87407805e+02  1.83850479e+03
  1.38927296e+03  1.78361285e+03  1.12847065e+03  1.23255777e+03
  5.92935602e+02  1.63845066e+03  5.12482326e+02  5.17676863e+02
  2.87071500e+02  4.25673103e+02  1.26315547e+03  1.85668749e+02
  6.93866612e+02  1.25597031e+03  1.69165738e+03 -1.14109610e+01
  7.49

### 10. Модуль NumPy. Закрепление знаний

In [ ]:
#задание на платформе:
from hidden import a, b
# Пишите здесь команды, который помогут
# найти ответы на вопросы
import numpy as np
print(np.int64(a)+np.int64(b))

In [5]:
def get_chess(a):
    arr = np.zeros((a, a))
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr
get_chess(4)

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [7]:
def shuffle_seed(array):
    seed = np.random.randint(2 ** 32, dtype=np.uint32)
    np.random.seed(seed)
    result = np.random.permutation(array)
    return result, seed
array = [1, 2, 3, 4, 5]
shuffle_seed(array)

(array([3, 4, 1, 2, 5]), 2560527389)

In [ ]:
def min_max_dist(*vectors):
    pass
    # Напишите тело функции

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
 
min_max_dist(vec1, vec2, vec3)